# Generated by Django 2.2.6 on 2019-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='case',
            name='created',
        ),
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(default='descricao', max_length=500),
            preserve_default=False,
        ),
    ]
